# Generated by Django 3.0.1 on 2021-03-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'user information',
                'verbose_name_plural': 'user informations',
                'db_table': 'user_tb',
                'ordering': ('id',),
            },
        ),
    ]
